// 首页中间件概览区块配置：8 种中间件类型
// 每种类型定义：key、展示名、图标、跳转 tab、TopN 主指标、辅助指标、聚合接口
import redisIcon from '../../assets/img/redis.svg'
import mysqlIcon from '../../assets/img/mysql.svg'
import postgresIcon from '../../assets/img/postgresql.svg'
import nginxIcon from '../../assets/img/nginx.svg'
import kafkaIcon from '../../assets/img/Kafka.svg'
import dockerIcon from '../../assets/img/docker.svg'
import rocketmqIcon from '../../assets/img/rocketMQ.svg'
import k8sIcon from '../../assets/img/kubernetes.svg'

export const middlewareTypes = [
  {
    key: 'redis',
    label: 'Redis',
    icon: redisIcon,
    tab: 'redis',
    endpoint: '/api/v1/middleware/redis/instances',
    topKey: 'usedMemory',
    topLabel: '内存占用',
    fmt: 'bytes',
    subKey: 'connectedClients',
    subLabel: '连接数',
    subFmt: 'num0',
  },
  {
    key: 'mysql',
    label: 'MySQL',
    icon: mysqlIcon,
    tab: 'mysql',
    endpoint: '/api/v1/middleware/mysql/instances',
    topKey: 'queriesPerSec',
    topLabel: 'QPS',
    fmt: 'num',
    subKey: 'threadsConnected',
    subLabel: '连接数',
    subFmt: 'num0',
  },
  {
    key: 'postgres',
    label: 'PostgreSQL',
    icon: postgresIcon,
    tab: 'postgres',
    endpoint: '/api/v1/middleware/postgres/instances',
    topKey: 'cacheHitRatio',
    topLabel: '缓存命中率',
    fmt: 'pct',
    subKey: 'numbackends',
    subLabel: '后端数',
    subFmt: 'num0',
  },
  {
    key: 'nginx',
    label: 'Nginx',
    icon: nginxIcon,
    tab: 'nginx',
    endpoint: '/api/v1/middleware/nginx/instances',
    topKey: 'requests',
    topLabel: '请求数',
    fmt: 'num0',
    subKey: 'activeConnections',
    subLabel: '活跃连接',
    subFmt: 'num0',
  },
  {
    key: 'kafka',
    label: 'Kafka',
    icon: kafkaIcon,
    tab: 'kafka',
    endpoint: '/api/v1/middleware/kafka/instances',
    topKey: 'consumerLagMax',
    topLabel: '最大积压',
    fmt: 'num0',
    subKey: 'brokerCount',
    subLabel: 'Broker',
    subFmt: 'num0',
  },
  {
    key: 'docker',
    label: 'Docker',
    icon: dockerIcon,
    tab: 'docker',
    endpoint: '/api/v1/middleware/docker/containers',
    topKey: 'memPercent',
    topLabel: '内存占比',
    fmt: 'pct',
    subKey: 'cpuPercent',
    subLabel: 'CPU占比',
    subFmt: 'pct',
  },
  {
    key: 'rocketmq',
    label: 'RocketMQ',
    icon: rocketmqIcon,
    tab: 'rocketmq',
    endpoint: '/api/v1/middleware/rocketmq/instances',
    topKey: 'messageAccumulation',
    topLabel: '消息堆积',
    fmt: 'num0',
    subKey: 'brokerCount',
    subLabel: 'Broker',
    subFmt: 'num0',
  },
  {
    key: 'k8s',
    label: 'Kubernetes',
    icon: k8sIcon,
    tab: 'k8s',
    endpoint: '/api/v1/middleware/k8s/instances',
    topKey: 'nodesReady',
    topLabel: '就绪节点',
    fmt: 'pctNodes',
    subKey: 'podsRunning',
    subLabel: '运行Pod',
    subFmt: 'num0',
  },
]
